CREATE_DW = '''
CREATE TABLE DATE_DIM (
DATE_SK INT NOT NULL,
FULL_DATE DATE,
DAY_OF_WEEK TINYINT,
DAY_NUM_IN_MONTH TINYINT,
DAY_NUM_OVERALL SMALLINT,
DAY_NAME VARCHAR(9),
DAY_ABBREV CHAR(3),
WEEKDAY_FLAG CHAR(10),
WEEK_NUM_IN_YEAR TINYINT,
WEEK_NUM_OVERALL SMALLINT,
WEEK_BEGIN_DATE DATETIME,
WEEK_BEGIN_DATE_KEY INT,
MONTH TINYINT,
MONTH_NUM_OVERALL SMALLINT,
MONTH_NAME VARCHAR(9),
MONTH_ABBREV CHAR(3),
QUARTER TINYINT,
YEAR SMALLINT,
YEARMO INT,
FISCAL_MONTH TINYINT,
FISCAL_QUARTER TINYINT,
FISCAL_YEAR SMALLINT,
PRIMARY KEY (DATE_SK)
);

CREATE TABLE CUSTOMER_DIM (
 CUSTOMER_SK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 CUSTOMER_ID VARCHAR(25) NOT NULL,
 CUSTOMER_NAME VARCHAR(500),
 SEGMENT VARCHAR(500)
);

CREATE TABLE LOCATION_DIM (
 LOCATION_SK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 COUNTRY VARCHAR(255),
 CITY VARCHAR(255),
 STATE VARCHAR(255),
 POSTAL_CODE VARCHAR(15)
 );
 
 CREATE TABLE PRODUCT_DIM (
 PRODUCT_SK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 PRODUCT_ID VARCHAR(25),
 CATEGORY VARCHAR(255) NOT NULL,
 SUB_CATEGORY VARCHAR(255),
 PRODUCT_NAME VARCHAR(255)
 );
 
 
 CREATE TABLE REGION_DIM (
 REGION_SK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 REGION_NAME VARCHAR(255) NOT NULL
);
 
 CREATE TABLE SHIPMODE_DIM (
 SHIPMODE_SK INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 SHIPMODE_NAME VARCHAR(255) NOT NULL
);
  
 
 CREATE TABLE ORDERS_FACT (
 ORDER_DATE INT NOT NULL,
 REGION_SK INT,
 SHIP_DATE INT NOT NULL,
 SALES DECIMAL(18,2),
 QUANTITY DECIMAL(18,2),
 PROFIT DECIMAL(18,2),
 DISCOUNT DECIMAL(18,2),
 CUSTOMER_SK INT,
 PRODUCT_SK INT,
 LOCATION_SK INT,
 ORDER_ID VARCHAR(20),
 SHIPMODE_SK INT,
 CONSTRAINT SHIPMODE_SK_FK
 FOREIGN KEY (SHIPMODE_SK) REFERENCES SHIPMODE_DIM(SHIPMODE_SK),
 CONSTRAINT REGION_SK_FK
 FOREIGN KEY (REGION_SK) REFERENCES REGION_DIM(REGION_SK),
 CONSTRAINT CUSTOMER_SK_FK
 FOREIGN KEY (CUSTOMER_SK) REFERENCES CUSTOMER_DIM(CUSTOMER_SK),
 CONSTRAINT PRODUCT_SK_FK
 FOREIGN KEY (PRODUCT_SK) REFERENCES PRODUCT_DIM(PRODUCT_SK),
 CONSTRAINT LOCATION_SK_FK
 FOREIGN KEY (LOCATION_SK) REFERENCES LOCATION_DIM(LOCATION_SK),
 CONSTRAINT ORDER_DATE_FK
 FOREIGN KEY (ORDER_DATE) REFERENCES DATE_DIM(DATE_SK),
  CONSTRAINT SHIP_DATE_FK
 FOREIGN KEY (SHIP_DATE) REFERENCES DATE_DIM(DATE_SK)
 );
'''